# Generated by Django 4.1.7 on 2023-03-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='хобби')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='название')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('place_phone', models.CharField(max_length=20, verbose_name='телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.place')),
                ('free_table', models.IntegerField(verbose_name='свободные места')),
                ('average_paycheck', models.FloatField(verbose_name='средний чек')),
            ],
            bases=('catalog.place',),
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.place')),
                ('free_table', models.IntegerField(verbose_name='свободные места')),
                ('average_paycheck', models.FloatField(verbose_name='средний чек')),
            ],
            bases=('catalog.place',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.place')),
                ('free_table', models.IntegerField(verbose_name='свободные места')),
                ('average_paycheck', models.FloatField(verbose_name='средний чек')),
            ],
            bases=('catalog.place',),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='фамилия')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('status', models.CharField(choices=[('h', 'host'), ('g', 'guest'), ('f', 'friend'), ('n', 'noone')], default='n', max_length=1, verbose_name='статус')),
                ('hobbies', models.ManyToManyField(to='catalog.hobbies')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(verbose_name='рейтинг')),
                ('comment', models.CharField(max_length=100, verbose_name='комментарий')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.users')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=200, verbose_name='название встречи')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.users')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.users',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.users',),
        ),
    ]
