# Generated by Django 4.1.6 on 2023-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_users_options_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='free_table',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='free_table',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='free_table',
        ),
        migrations.AddField(
            model_name='bar',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='описание заведения'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='описание заведения'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='meeting_description',
            field=models.CharField(max_length=300, null=True, verbose_name='описание встречи'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='описание заведения'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='average_paycheck',
            field=models.FloatField(null=True, verbose_name='средний чек'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='average_paycheck',
            field=models.FloatField(null=True, verbose_name='средний чек'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='хобби'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meeting_name',
            field=models.CharField(max_length=200, verbose_name='названиие встречи'),
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='user',
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(max_length=100, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_paycheck',
            field=models.FloatField(null=True, verbose_name='средний чек'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('h', 'host'), ('g', 'guest'), ('n', 'noone')], default='n', max_length=1, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='user',
            field=models.ManyToManyField(to='catalog.users'),
        ),
    ]
