# Generated by Django 4.1.6 on 2023-04-12 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_remove_bar_free_table_remove_cafe_free_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
