# Generated by Django 4.1.6 on 2023-04-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_users_id_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobbies',
            options={'verbose_name_plural': 'Хобби'},
        ),
        migrations.AlterModelOptions(
            name='meetings',
            options={'verbose_name_plural': 'Встречи'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Заведения'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': 'Рейтинг'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='id_user',
        ),
        migrations.AddField(
            model_name='meetings',
            name='date_meeting',
            field=models.DateField(null=True, verbose_name='Дата встречи'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='time_meeting',
            field=models.TimeField(null=True, verbose_name='Время встречи'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_photo',
            field=models.ImageField(blank=True, null=True, upload_to='place_photo'),
        ),
        migrations.AddField(
            model_name='rating',
            name='meetings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.meetings'),
        ),
        migrations.AddField(
            model_name='rating',
            name='meetings_rating',
            field=models.PositiveIntegerField(null=True, verbose_name='рейтинг встречи'),
        ),
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(max_length=300, null=True, verbose_name='комментарий'),
        ),
    ]
