# Generated by Django 4.1.6 on 2023-04-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_hobbies_options_alter_meetings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='place_rating',
            field=models.PositiveIntegerField(null=True, verbose_name='рейтинг заведения'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_rating',
            field=models.PositiveIntegerField(null=True, verbose_name='рейтинг пользователя'),
        ),
    ]
