# Generated by Django 4.1.6 on 2023-04-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_rating_rating_rating_place_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'verbose_name_plural': 'Бар'},
        ),
        migrations.AlterModelOptions(
            name='cafe',
            options={'verbose_name_plural': 'Кафе'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'Ресторан'},
        ),
        migrations.AddField(
            model_name='place',
            name='place_site',
            field=models.URLField(max_length=50, null=True, verbose_name='сайт заведения'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='average_paycheck',
            field=models.FloatField(null=True, verbose_name='средний чек(BYN)'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='average_paycheck',
            field=models.FloatField(null=True, verbose_name='средний чек(BYN)'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.place'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.users'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_paycheck',
            field=models.FloatField(null=True, verbose_name='средний чек(BYN)'),
        ),
    ]
