# Generated by Django 4.1.6 on 2023-04-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_users_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'verbose_name_plural': 'Бары'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'Рестораны'},
        ),
        migrations.AlterField(
            model_name='bar',
            name='description',
            field=models.TextField(max_length=400, null=True, verbose_name='описание заведения'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='description',
            field=models.TextField(max_length=400, null=True, verbose_name='описание заведения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_photo',
            field=models.ImageField(blank=True, default='default_place.jpg', upload_to='place_photo'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(max_length=300, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(max_length=400, null=True, verbose_name='описание заведения'),
        ),
    ]
